// generated by lib/sync.js
   // This is a required an autogenerated file from the Zesty.io NextJS integration
   // This file is overwritten everytime the integration script is run
       
   import Clipping from './Clipping';
import Homepage from './Homepage';
import Service from './Service';
import Contactpage from './Contactpage';
import Team from './Team';
import Project from './Project';
   
   export {
     Clipping, Homepage, Service, Contactpage, Team, Project
   }